### ISSUE TITLE
Bug: backspace deletes two characters on android chrome for rich text editor

### ISSUE THREAD

**Issue by kirandash** [konstantinmuenster/lexical-examples#1]
### Link to reproduction

[Lexical Examples Demo](https://lexical-examples-demo.vercel.app/)

### Describe the Bug

**Current behaviour:**
Hitting backspace in middle of content deletes two characters on Android chrome

**The expected behavior:**
Only the character before the cursor gets deleted

### To Reproduce

1. Open the editor on Chrome on Android
2. Write a word
3. Put the cursor somewhere in the middle
4. hit backspace - two characters get deleted. One character from front and one from back

**Comment by petyosi** [comment]
This is likely a problem in Lexical itself. I'm afraid I don't have a testing device, can you [try if it's broken here as well](https://playground.lexical.dev/)?

**Comment by kirandash** [comment]
@konstantinmuenster  FYI, this is a lexical issue and as pointed out by lexical, the root cause is the issue from android chrome. 

https://github.com/facebook/lexical/issues/4941

But I am curious if you have faced this issue and managed to find a patch for this. Since the issue from lexical is there since almost a year and no fixes/patch is known ASFAI.

**Comment by konstantinruge** [comment]
Hey @kirandash and sorry for my late reply! 

Just saw that you already filed a PR in facebook/lexical - that's awesome 🙌 Thanks for the great community work!
